# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_datetime', models.DateTimeField()),
                ('zipcode', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('temperature_f', models.DecimalField(decimal_places=1, max_digits=4)),
                ('response_datetime', models.DateTimeField()),
            ],
        ),
    ]
