# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperatures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temperature',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='temperature',
            name='type_of_request',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
    ]
