# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperatures', '0002_auto_20160710_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='response_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='temperature_f',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
    ]
